### ISSUE TITLE
Ground collision offset.

### ISSUE THREAD

**Issue by jasonjmcghee** [cjdell/web-blocks#11]
Showing is me "standing" on a cube. If I center myself, I fall.
![image](https://cloud.githubusercontent.com/assets/1522149/15638237/d1a7bd84-25d2-11e6-823d-e4dd13c45e11.png)

**Comment by cjdell** [comment]
I know the collision detection is dodgy, could do with some help from a games developer. I know it's also possible to get stuck when climbing a mountain. I intend to rewrite the collision detection code at some point (it's awful) but it's not going to be a small job and it mostly works well enough for now. :-)
