### ISSUE TITLE
Add mini on-screen console accessible by hitting "enter"

### ISSUE THREAD

**Issue by jasonjmcghee** [cjdell/web-blocks#14]
I think it'd be great to add an on-screen mini console that showed console output and let users execute methods they created. This way they could start with printing "hello world", or easily finding their position, for example. There are probably a number of much better examples, but I imagine you can see why this could be useful.

**Comment by cjdell** [comment]
This is a great idea. How about the console has 3 states. We already have console on/off, but we could add a third which is effectively split screen, with the console at the bottom and the viewport at the top. It would be like using the browser dev tools. Could even have it as a popup window which breaks out of the main window, so the user can move/resize as they wish?

**Comment by jasonjmcghee** [comment]
#### That could definitely work too.

(Just to give you insight into what I was imagining)
At time of logging this feature request, I was thinking more along the lines of a single line console in the bottom left that is invisible unless you hit enter, then it shows up with a slightly opaque input bar, where it's effectively a console (with history). Output would be listed above (newest nearest to console line). So printed messages would just show up on screen. I imagined users being able to (for example) write a program like: create a "quest" which is a function checked every 100ms or something, like `setInterval(() => if (getPosition().pos.y > 100) console.log("Congrats on reaching new heights!"), 100)` which would print the message on the screen when they somehow reached a height greater than 100. You could also control it and do something like `print()` instead so you could pipe it to the screen.

**Comment by jasonjmcghee** [comment]
For the separate window, would this be communication through cookies? There might have to be an event system which listens to changes in the cookies. I don't think it's realistic to have session ids and create communication between server-side and clients.
